set(headers
	common/IArchive.h
	common/IBufferStream.h
	common/IConsole.h
	common/ICriticalSection.h
	common/IDataStream.h
	common/IDatabase.h
	common/IDebugLog.h
	common/IDirectoryIterator.h
	common/IDynamicCreate.h
	common/IErrors.h
	common/IEvent.h
	common/IFIFO.h
	common/IFileStream.h
	common/IInterlockedLong.h
	common/ILinkedList.h
	common/IMemPool.h
	common/IMutex.h
	common/IPipeClient.h
	common/IPipeServer.h
	common/IPrefix.h
	common/IRangeMap.h
	common/IReadWriteLock.h
	common/ISegmentStream.h
	common/ISingleton.h
	common/ITextParser.h
	common/IThread.h
	common/ITimer.h
	common/ITypes.h
)
