set(sources
	common/IArchive.cpp
	common/IBufferedFileStream.cpp
	common/IBufferStream.cpp
	common/IConsole.cpp
	common/IDataStream.cpp
	common/IDatabase.cpp
	common/IDebugLog.cpp
	common/IDirectoryIterator.cpp
	common/IDynamicCreate.cpp
	common/IErrors.cpp
	common/IEvent.cpp
	common/IFIFO.cpp
	common/IFileStream.cpp
	common/IInterlockedLong.cpp
	common/IMemPool.cpp
	common/IMutex.cpp
	common/IPipeClient.cpp
	common/IPipeServer.cpp
	common/IPrefix.cpp
	common/IRangeMap.cpp
	common/IReadWriteLock.cpp
	common/ISegmentStream.cpp
	common/ISingleton.cpp
	common/ITextParser.cpp
	common/IThread.cpp
	common/ITimer.cpp
	common/ITypes.cpp
)
